name: Awesome The Hague

collections:
  submissions:
    output: true

# Sass settings
sass:
    sass_dir: _scss
    style: :compressed

github: [metadata]

navlinks:
- title: Pitch Nights
  url: /pitch-nights
  id: pitch-nights
- title: Trustees
  url: /trustees
  id: trustees
- title: Inzendingen
  url: /inzendingen
  id: inzendingen
- title: Partners
  url: /partners
  id: partners
- title: FAQ
  url: /faq
  id: faq
